# Generated by Django 2.2.4 on 2019-08-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190822_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagee',
            new_name='image',
        ),
    ]
